# Generated by Django 3.2 on 2023-06-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_photo_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ManyToManyField(blank=True, default='cow-dance-animal.gif', to='users.Photo', verbose_name='Фото'),
        ),
    ]
