# Generated by Django 3.2.13 on 2023-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230627_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ManyToManyField(blank=True, to='users.Photo', verbose_name='Фото'),
        ),
    ]
