# Generated by Django 3.2 on 2023-06-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230628_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Видео файл'),
        ),
    ]
