# Generated by Django 3.2.16 on 2023-07-02 17:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_videofile_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Новость'),
        ),
    ]
