# Generated by Django 3.2.13 on 2023-07-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_news_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='users.Tags', verbose_name='Тэг'),
        ),
    ]
