version: '3'

services:
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DB=Django
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=Django
  redis:  # Добавляем сервис Redis
    image: redis:latest

volumes:
  todo-mysql-data:
