# Generated by Django 3.2.13 on 2023-03-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/news/downloads', verbose_name='Фото сотрудника')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('body', models.TextField(blank=True, null=True, verbose_name='О сотруднике')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Сотрудник ВУЗа',
                'verbose_name_plural': 'Сотрудники ВУЗа',
            },
        ),
    ]
