# Generated by Django 3.2.13 on 2023-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathedra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото сотрудника'),
        ),
    ]
