# Generated by Django 3.2 on 2023-06-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathedra', '0002_alter_teachers_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(blank=True, default='cow-dance-animal.gif', null=True, upload_to='', verbose_name='Фото сотрудника'),
        ),
    ]
