# Generated by Django 3.2.13 on 2023-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathedra', '0003_auto_20230627_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(blank=True, default='no-avatar.jpg', null=True, upload_to='', verbose_name='Фото сотрудника'),
        ),
    ]
