# Generated by Django 4.1.1 on 2022-10-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/news/downloads', verbose_name='Фото сотрудника')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('body', models.TextField(blank=True, null=True, verbose_name='О сотруднике')),
            ],
            options={
                'verbose_name': 'Сотрудники ВУЗа',
            },
        ),
    ]
