# Generated by Django 4.1.1 on 2022-10-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teachersadd_options_alter_teachersadd_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersadd',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
