# Generated by Django 4.1.1 on 2022-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(null=True, verbose_name='Новость')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('photo', models.ImageField(null=True, upload_to='static/news/downloads', verbose_name='Фото')),
                ('files', models.FileField(null=True, upload_to='static/news/downloads', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
