# Generated by Django 4.1.1 on 2022-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsadd',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='newsadd',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='static/news/downloads', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='newsadd',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/news/downloads', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='newsadd',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
